# Generated by Django 2.1.7 on 2020-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='startDate',
            field=models.DateField(),
        ),
    ]
